import turtle
import math
import tkinter as tk
from Calculadora_de_dinámica_OS import num1, num2

a1 = num1()
Fuerza_ang = num2()
ventana = Calculadora_de_dinámica_OS

def plup():
    if Fuerza_ang != "":
        fz = float(Fuerza_ang)
        a3 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)
        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)
        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a3 - 90

        cc = math.cos(math.radians(a3)) * 300
        co = math.cos(math.radians(a2)) * 300
        
        # velocidad del lapiz
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(-50, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a3)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a3)
        t.forward(295)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('red')
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.left(270)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(a2 + 180)
                            
        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(20)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
    
        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.right(45)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(-45)
        t.penup()
        t.forward(5)
        t.pendown()

        # Lineas de ejes
        t.pensize(3)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(20)
        t.pendown()

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')
        
        t.left(180)
        t.forward(15)
        t.right(90)
        t.backward(15)
        t.forward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('lightgreen')
        t.right(180)
        t.right(fz)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(-fz)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')
    
        t.penup()
        t.setpos(-150, -30)
        t.pendown()
    
        # Quadrado
        t.right(90 + a3)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)
    
        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)
    
        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)
    
        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)
    
        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)
    
        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

    else:

        a3 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)
        
        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a3 - 90

        cc = math.cos(math.radians(a3)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(-50, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a3)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a3)
        t.forward(295)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('red')
        t.left(0)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(90)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('lightgreen')

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('lightgreen')

        t.left(-a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.right(135)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)

        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.right(45)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(-45)
        t.penup()
        t.forward(5)
        t.pendown()
                        
        # Lineas de ejes
        t.pensize(3)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha Fuerza de friccion (Fr)
        t.pencolor('lightgreen')
        t.pendown()
        t.left(135)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(270)
        t.backward(15)
        t.left(a2)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.left(90)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90    )
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

def plup2_1():
    
    if Fuerza_ang != "":
        
        fz = float(Fuerza_ang)
        a4 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)

        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a4 - 90

        cc = math.cos(math.radians(a4)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        #   Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(0, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a4)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a4)
        t.forward(165)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)

        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.left(45)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(-45)
        t.penup()
        t.forward(5)
        t.pendown()

        # Lineas de ejes
        t.pensize(3)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('lightgreen')
        t.left(fz)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.left(-fz)
        t.left(270)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(-a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.right(135)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha Fuerza de friccion (Fr)
        t.pencolor('red')
        t.pendown()
        t.left(135)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(270)
        t.backward(15)
        t.left(a2)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.left(90)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

    else:

        a4 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)
        
        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a4 - 90

        cc = math.cos(math.radians(a4)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(0, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a4)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a4)
        t.forward(165)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
                        
        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.left(45)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(-45)
        t.penup()
        t.forward(5)
        t.pendown()
    
        # Lineas de ejes
        t.pensize(3)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('lightgreen')
        t.left(0)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(90)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(-a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.right(135)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha Fuerza de friccion (Fr)
        t.pencolor('red')
        t.pendown()
        t.left(135)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(270)
        t.backward(15)
        t.left(a2)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.left(90)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)
    
        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)
    
        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

def plup2_2():

    if Fuerza_ang != "":
        
        fz = float(Fuerza_ang)
        a4 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)

        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a4 - 90

        cc = math.cos(math.radians(a4)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(0, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a4)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a4)
        t.forward(165)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)
        
        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('red')
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.left(270)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135) 
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(a2 + 180)
                        
        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(20)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)

        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.right(45)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(-45)
        t.penup()
        t.forward(5)
        t.pendown()

        # Lineas de ejes
        t.pensize(3)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(20)
        t.pendown()

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')
                        
        t.left(180)
        t.forward(15)
        t.right(90)
        t.backward(15)
        t.forward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('lightgreen')
        t.right(180)
        t.right(fz)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(-fz)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.right(90 + a4)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)
    
        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

    else:
        
        a4 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)
            
        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a4 - 90

        cc = math.cos(math.radians(a4)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(0, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a4)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a4)
        t.forward(165)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('red')
        t.left(0)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(90)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('lightgreen')

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('lightgreen')

        t.left(-a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.right(135)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)

        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.right(45)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(180)
        t.forward(10)
        t.right(90)
        t.forward(10)
        t.right(180)
        t.forward(20)
        t.right(-45)
        t.penup()
        t.forward(5)
        t.pendown()
                        
        # Lineas de ejes
        t.pensize(3)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha Fuerza de friccion (Fr)
        t.pencolor('lightgreen')
        t.pendown()
        t.left(135)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(270)
        t.backward(15)
        t.left(a2)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.left(90)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

def plup3():

    if Fuerza_ang != "":
                
        fz = float(Fuerza_ang)
        a5 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)
            
        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a5 - 90

        cc = math.cos(math.radians(a5)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(0, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a5)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a5)
        t.forward(50)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
                
        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.left(45)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(-45)
        t.penup()
        t.forward(5)
        t.pendown()
                
        # Lineas de ejes
        t.pensize(3)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('lightgreen')
        t.left(fz)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.left(-fz)
        t.left(270)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(-a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.right(135)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha Fuerza de friccion (Fr)
        t.pencolor('red')
        t.pendown()
        t.left(135)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(270)
        t.backward(15)
        t.left(a2)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.left(90)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()

    else:

        a5 = float(a1)

        lienzo_turtle = turtle.ScrolledCanvas(ventana)
        lienzo_turtle.grid(column=6, row=1, columnspan=4, rowspan=8, padx=10, pady=10)

        # Crear un objeto Turtle en el lienzo
        t = turtle.RawTurtle(lienzo_turtle)
        
        # Pide los ángulos de los dos ángulos desconocidos
        a2 = - a5 - 90

        cc = math.cos(math.radians(a5)) * 300
        co = math.cos(math.radians(a2)) * 300

        # Configura la tortuga
        t.speed(100)

        # Definir el tamaño de la línea y el color del trazo
        t.pensize(7)
        t.pencolor('gray')

        t.penup()
        t.setpos(0, -150)
        t.pendown()

        # Dibuja el triángulo rectángulo
        t.left(a5)
        t.forward(50)
        t.forward(250)
        t.left(a2)
        t.backward(co)

        # Angulo de 90º
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(30)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(30)

        # Dibuja el triángulo rectángulo
        t.pensize(7)
        t.pencolor('gray')
        t.left(90)
        t.forward(30)
        t.left(90)
        t.backward(cc)
        t.left(a5)
        t.forward(50)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(15)

        # Flecha de Fuerza Normal (N)
        t.pensize(3)
        t.pencolor('blue')
        t.left(90)
        t.forward(15)

        # Lineas de ejes
        t.pencolor('black')
        t.left(90)
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
                
        # letra X
        t.pensize(2)
        t.penup()
        t.forward(5)
        t.pendown()
        t.left(45)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(20)
        t.left(-45)
        t.penup()
        t.forward(5)
        t.pendown()
                
        # Lineas de ejes
        t.pensize(3)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha de Fuerza 
        t.pensize(3)
        t.pencolor('lightgreen')
        t.left(0)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)
        t.right(90)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(15)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(15)
        t.pendown()

        # Flecha Fuerza (N)
        t.pencolor('blue')
        t.pendown()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.right(135)
        t.forward(15)
        t.left(45)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Letra Y
        t.pendown()
        t.left(300)
        t.pensize(2)
        t.forward(20)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(270)
        t.forward(10)

        # Lineas de ejes
        t.pensize(2)
        t.right(300)
        t.penup()
        t.forward(5)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha de Fuerza Normal (N)
        t.pencolor('blue')
        t.pendown()
        t.right(45)
        t.forward(15)
        t.left(135)
        t.forward(20)
        t.left(135)
        t.forward(15)
        t.left(180)
        t.forward(15)
        t.right(135)
        t.forward(10)
        t.left(90)
        t.forward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(90)
        t.backward(15)
        t.left(90)
        t.backward(15)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(90)
        t.backward(15)

        # Flecha de Peso (P)
        t.pensize(3)
        t.pencolor('gold')

        t.left(a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(40)

        # Flecha Fuerza de friccion (Fr)
        t.pensize(3)
        t.pencolor('red')

        t.left(-a2)
        t.backward(40)
        t.left(90)
        t.backward(10)
        t.right(135)
        t.backward(15)
        t.right(135)

        # Lineas de ejes
        t.pencolor('black')
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)
        t.pendown()
        t.forward(10)
        t.penup()
        t.forward(5)

        # Flecha Fuerza de friccion (Fr)
        t.pencolor('red')
        t.pendown()
        t.left(135)
        t.backward(15)
        t.left(135)
        t.backward(20)
        t.left(135)
        t.backward(15)
        t.left(180)
        t.backward(15)
        t.right(135)
        t.backward(10)
        t.left(90)
        t.backward(25)

        # Cuerpo
        t.pensize(3)
        t.pencolor('black')

        t.left(270)
        t.backward(15)
        t.left(a2)

        # Cuadro de leyenda
        t.pensize(3)
        t.pencolor('black')

        t.penup()
        t.setpos(-150, -30)
        t.pendown()

        # Quadrado
        t.left(90)
        t.forward(50)

        # Primera linea divisoria
        t.left(90)
        t.forward(30)

        # Letra F
        t.pencolor('lightgreen')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(55)

        # Letra F de Fr
        t.pencolor('red')
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(10)
        t.left(90)
        t.forward(10)
        t.left(180)
        t.forward(10)
        t.left(90)
        t.forward(20)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(270)
        t.forward(15)
        t.left(180)
        t.forward(25)

        # Letra R de Fr
        t.pencolor('red')
        t.left(90)
        t.forward(16)
        t.left(180)
        t.forward(4)
        t.left(90)
        t.forward(7)
        t.right(90)
        t.forward(3)
        t.left(180)
        t.forward(3)
        t.left(90)
        t.forward(7)
        t.left(90)
        t.forward(12)

        # Primera linea divisoria
        t.pencolor('black')
        t.left(90)
        t.forward(75)

        # Quadrado
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(15)

        # Letra N
        t.pencolor('blue')
        t.left(90)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)
        t.right(180)
        t.forward(30)
        t.left(215)
        t.forward(37)
        t.right(215)
        t.forward(30)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(35)

        # Segunda linea divisoria
        t.left(90)
        t.forward(100)
        t.left(180)
        t.forward(100)

        # Quadrado
        t.left(90)
        t.forward(20)

        # Letra P
        t.pencolor('Gold')
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.right(90)
        t.forward(15)
        t.left(90)
        t.forward(15)

        # Quadrado
        t.pencolor('black')
        t.left(90)
        t.forward(30)

        # Esconder el lapiz
        t.penup()
        t.setpos(-320, -280)
        t.pendown()
        t.forward(1)
        t.hideturtle()